title: "[42 gennaio 2024 (scrivi la data corretta al suo posto)] Descrizione"
labels: ["da risolvere"]
body:
- type: textarea
  attributes:
    label: Traccia
    description: Inserisci la traccia dell'esercizio come testo o screenshot (includi anche eventuali immagini)
  validations:
    required: true
- type: textarea
  attributes:
    label: Soluzione del Prof
    description: Includi un'eventuale soluzione del professore (se in tuo possesso). Una volta completato l'inserimento della discussion potrai aggiungere, come commento, anche una tua eventuale proposta di soluzione 🙂
  validations:
    required: false
