title: "[42 gennaio 2024 (scrivi la data dell'appello al suo posto)] Pipeline"
labels: ["da risolvere", "pipeline"]
body:
- type: textarea
  attributes:
    label: Traccia
    description: Inserisci la traccia dell'esercizio come testo e/o screenshot. Puoi consultare qui un esempio: https://github.com/sapienzastudentsnetwork/architettura-degli-elaboratori/discussions/80
  validations:
    required: true
- type: textarea
  attributes:
    label: Soluzione del Prof
    description: Includi un'eventuale soluzione del professore (se in tuo possesso). Una volta completato l'inserimento della discussion potrai aggiungere, come commento, anche una tua eventuale proposta di soluzione 🙂
  validations:
    required: false
